# -*- coding: utf-8 -*-
"""titanic-data-demo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AqgaxBnvKqBU2sfqYjoVXcxAsQld5L7j
"""

import pandas as pd
df = pd.read_csv("https://gist.githubusercontent.com/fyyying/4aa5b471860321d7b47fd881898162b7/raw/6907bb3a38bfbb6fccf3a8b1edfb90e39714d14f/titanic_dataset.csv")
df

# Q1: EDA initial overview (use existing df)
print("=== SHAPE ===")
print(df.shape)
print()


print("\n=== HEAD (first 10 rows) ===")
print(df.head(10))
print()


print("\n=== INFO ===")
df.info()
print()


print("\n=== DESCRIBE (all columns) ===")
print(df.describe(include='all').T)
print()



print("\n=== Missing values per column ===")
print(df.isna().sum())

import pandas as pd
import matplotlib.pyplot as plt
# أنسب طريقة لعرض head في نوتبوك (Colab / Jupyter)
from IPython.display import display
display(df.head(10))

# فرضاً عندنا الـ DataFrame df
# نعرض أول 10 صفوف كجدول
fig, ax = plt.subplots(figsize=(10, 4))
ax.axis('off')
tbl = ax.table(cellText=df.head(10).values, colLabels=df.columns, loc='center')
plt.title("First 10 Rows of the DataFrame")
plt.show()

df['Sex'].value_counts()

import matplotlib.pyplot as plt
import seaborn as sns

# نرسم التوزيع حسب الجنس
plt.figure(figsize=(6,4))
sns.countplot(x='Sex', data=df, palette='coolwarm')

plt.title("Distribution of Passengers by Gender")
plt.xlabel("Gender")
plt.ylabel("Count")
plt.grid(axis='y', linestyle='--', alpha=0.5)
plt.show()

df['Survived'].value_counts()
import matplotlib.pyplot as plt
import seaborn as sns

# نرسم توزيع البقاء على قيد الحياة
plt.figure(figsize=(6,4))
sns.countplot(x='Survived', data=df, palette='viridis')

plt.title("Distribution of Survival on Titanic")
plt.xlabel("Survival (0 = Died, 1 = Survived)")
plt.ylabel("Count")
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

df.groupby('Survived')['Age'].mean()


import matplotlib.pyplot as plt
import seaborn as sns

# نجمع البيانات ونحسب المتوسط
age_means = df.groupby('Survived')['Age'].mean().reset_index()
print(age_means)
print()
print()
# نرسم البار
plt.figure(figsize=(6,4))
sns.barplot(x='Survived', y='Age', data=age_means, palette='viridis')

plt.title("Average Age by Survival Status")
plt.xlabel("Survival (0 = Died, 1 = Survived)")
plt.ylabel("Average Age")
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

df.groupby('Pclass')['Age'].mean()
import matplotlib.pyplot as plt
import seaborn as sns

# نحسب المتوسطات ونحولها لجدول
pclass_age_means = df.groupby('Pclass')['Age'].mean().reset_index()

# نرسم البار
plt.figure(figsize=(6,4))
sns.barplot(x='Pclass', y='Age', data=pclass_age_means, palette='coolwarm')

plt.title("Average Age by Passenger Class")
plt.xlabel("Passenger Class")
plt.ylabel("Average Age")
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

df.groupby(['Pclass', 'Sex'])['Survived'].mean()

import matplotlib.pyplot as plt
import seaborn as sns

# نحسب المتوسطات ونحولها لجدول
survival_rates = df.groupby(['Pclass', 'Sex'])['Survived'].mean().reset_index()

# نرسم البار مع Hue للجنس
plt.figure(figsize=(8,5))
sns.barplot(x='Pclass', y='Survived', hue='Sex', data=survival_rates, palette='viridis')

plt.title("Survival Rate by Pclass and Sex")
plt.xlabel("Passenger Class")
plt.ylabel("Survival Rate")
plt.ylim(0,1)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

# نحسب المتوسط لسعر التذكرة
avg_fare = df['Fare'].mean()

# نعمل مجموعتين: أغلى من المتوسط وأرخص من المتوسط
high_fare = df[df['Fare'] > avg_fare]
low_fare = df[df['Fare'] <= avg_fare]

# نطبع معدل النجاة لكل مجموعة
print("متوسط السعر:", avg_fare)
print("معدل نجاة الأغنياء:", high_fare['Survived'].mean())
print("معدل نجاة الفقراء:", low_fare['Survived'].mean())

import matplotlib.pyplot as plt
import seaborn as sns

# نحضر جدول صغير للرسم
fare_survival = pd.DataFrame({
    'Group': ['High Fare', 'Low Fare'],
    'Survival Rate': [high_fare['Survived'].mean(), low_fare['Survived'].mean()]
})

# نرسم البار
plt.figure(figsize=(6,4))
sns.barplot(x='Group', y='Survival Rate', data=fare_survival, palette='viridis')

plt.title("Survival Rate by Fare Group")
plt.ylabel("Survival Rate")
plt.ylim(0,1)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

# نحسب نسبة النجاة لكل جنس
survival_by_sex = df.groupby('Sex')['Survived'].mean()

# نعرض النتيجة
print("نسبة النجاة لكل جنس:")
print(survival_by_sex)









import matplotlib.pyplot as plt
import seaborn as sns

plt.bar(survival_by_sex.index, survival_by_sex.values, color=['pink', 'lightblue'])
plt.title('نسبة النجاة لكل جنس')
plt.xlabel('الجنس')
plt.ylabel('نسبة النجاة')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()



